#Configuration:
  injectionMode: batch
  inputPath: /home/alex/work/testInput
  outputPath: /home/alex/work/testOutput
  
  singleRun:
    type: SWITCH_MISS_DEFAULT_FAULT
    locationPattern:
      packageP: 
      classP: WorkBench
      methodP: calculate
      variableP: 
    variableScope: 
    variableType: int
    action: 
    targetValue: 
    
  batchRun:
    counter: 10
    distributionMode: fix
    faultList:
    -
       type: SWITCH_MISS_DEFAULT_FAULT
       distribution: 1
       locationPattern:
         packageP: 
         classP: 
         methodP: 
       variableType: 
       action: 
 #   -
 #      type: ExceptionShortCircuit
 #      distribution: 0.5
 #      locationPattern:
 #        packageP: 
 #        classP: 
 #        methodP: \*try\*
 #      exceptionType: THROW
 #      action: FIRST 
 