#Configuration:
  injectionMode: batch
  inputPath: /home/alex/work/testInput
  outputPath: /home/alex/work/testOutput
  
  singleRun:
    type: Value_Fault
    locationPattern:
      packageP: 
      classP: 
      methodP: calculate
      variableP: 
    variableScope: 
    variableType: long
    action: 
    targetValue: 
    
  batchRun:
    counter: 2
    distributionMode: fix
    faultList:
    -
       type: Value_Fault
       distribution: 1
       locationPattern:
         packageP: com.oath
         classP: 
         methodP: 
       variableType: 
       action:  
 #   -
 #      type: ExceptionShortCircuit
 #      distribution: 0.5
 #      locationPattern:
 #        packageP: 
 #        classP: 
 #        methodP: \*try\*
 #      exceptionType: THROW
 #      action: FIRST 
 