#Configuration:
  injectionMode: batch
  inputPath:
  outputPath:
  
  singleRun:
    type: ValueFault
    locationPattern:
      packageP: 
      classP: 
      methodP: \*calculate\*
    variableType: long
    action: ADD
    
  batchRun:
    counter: 100
    distributionMode: fix
    faultList:
    -
       type: ValueFault
       distribution: 0.5
       locationPattern:
         packageP: 
         classP: 
         methodP: \*calculate\*
       variableType: LONG
       action: ADD 
    -
       type: ExceptionShortCircuit
       distribution: 0.5
       locationPattern:
         packageP: 
         classP: 
         methodP: \*try\*
       exceptionType: THROW
       action: FIRST 
 