#Configuration:
  injectionMode: single
  inputPath: /home/alex/work/testInput
  outputPath: /home/alex/work/testOutput
  debug: false
  activationMode: always 
  activationRate: 10
  
  singleRun:
    type: ATTRIBUTE_SHADOWED_FAULT
    locationPattern:
      packageP: 
      classP: WorkBench
      methodP: 
      variableP: 
    variableScope: catch
    variableType: int
    action: field2local
    targetValue: 
    
  batchRun:
    counter: 10
    distributionMode: fix
    faultList:
    -
       type: SWITCH_FALLTHROUGH_FAULT
       distribution: 1
       locationPattern:
         packageP: 
         classP: WorkBench
         methodP: calculate
       variableType: 
       action: 
 #   -
 #      type: ExceptionShortCircuit
 #      distribution: 0.5
 #      locationPattern:
 #        packageP: 
 #        classP: 
 #        methodP: \*try\*
 #      exceptionType: THROW
 #      action: FIRST 
 